[package]
name = "ractor"
version = "0.1.2"
authors = ["Sean Lawlor <seanlawlor@fb.com>"]
description = "A actor framework for Rust"
license = "MIT"
edition = "2018"
keywords = ["actor", "ractor"]
repository = "https://github.com/slawlor/ractor"
readme = "../README.md"
license-file = "../LICENSE"
homepage = "https://github.com/slawlor/ractor"
categories = ["actor"]

[dependencies]
async-trait = "0.1"
dashmap = "5"
futures = "0.3"
once_cell = "1"
tokio = { version = "1.23", features = ["rt", "time", "sync", "macros"]}

[dev-dependencies]
tokio = { version = "1.23", features = ["rt", "time", "sync", "macros", "rt-multi-thread"] }