[package]
name = "ractor"
version = "0.3.1"
authors = ["Sean Lawlor", "Evan Au", "Dillon George"]
description = "A actor framework for Rust"
documentation = "https://docs.rs/ractor"
license = "MIT"
edition = "2018"
keywords = ["actor", "ractor"]
repository = "https://github.com/slawlor/ractor"
readme = "../README.md"
homepage = "https://github.com/slawlor/ractor"
categories = ["actor", "erlang"]

[dependencies]
async-trait = "0.1"
dashmap = "5"
futures = "0.3"
once_cell = "1"
tokio = { version = "1.23", features = ["rt", "time", "sync", "macros"]}

[dev-dependencies]
function_name = "0.3"
tokio = { version = "1.23", features = ["rt", "time", "sync", "macros", "rt-multi-thread"] }